export enum TypeControl {
    NAME_ID_LIST,
    DATASET_ROW_CHECKBOX,
    LOGIN_AGREE_TO_TERMS_CHECKBOX,
    LOGIN_USER_NAME_INPUT,
    LOGIN_PASSWORD_INPUT,
    LOGIN_SUBMIT_BUTTON,
    EXPORT_FORMAT_RADIO_BUTTON,
    SAMPLE_LIST_TYPE_RADIO_BUTTON
}


