export enum TypeControl {
    NAME_ID_LIST,
    DATASET_ROW_CHECKBOX,
    LOGIN_AGREE_TO_TERMS_CHECKBOX,
    LOGIN_USER_NAME_INPUT,
    LOGIN_PASSWORD_INPUT,
    LOGIN_SUBMIT_BUTTON,
    EXPORT_FORMAT_RADIO_BUTTON,
    SAMPLE_LIST_TYPE_RADIO_BUTTON,
    SYSTEM_STATUS_MESSAGE_BODY,
    MARKER_SAMPLE_LIST_MODE_RADIO_BUTTON,
    FILE_SELECTOR_MARKER_SAMPLE_LIST_UPLOAD,
    SUBMIT_BUTTON_UPLOAD_MARKER_SAMPLE_LIST,
    SUBMIT_BUTTON_EXTRACT,
    CHECKBOX_LIST,
    CRITERIA_TREE,
    NAVIGATION_TABS
}


