package org.gobiiproject.gobiidao.resultset.core.listquery;

/**
 * Created by Phil on 10/25/2016.
 */
public enum ListSqlId {
    QUERY_ID_DATASET_ALL,
    QUERY_ID_CONTACT_ALL,
    QUERY_ID_ORGANIZATION_ALL,
    QUERY_ID_PLATFORM_ALL,
    QUERY_ID_PROJECT_ALL,
    QUERY_ID_EXPERIMENT_ALL,
    QUERY_ID_MARKER_ALL,
    QUERY_ID_MARKER_NAMES_ALL,
    QUERY_ID_PROTOCOL_ALL,
    QUERY_ID_CVS_BY_GROUP,
    QUERY_ID_LAST_MODIFIED,
    QUERY_ID_COUNT,
    QUERY_ID_COUNT_OF_CHILDREN,
    QUERY_ID_CV_BY_GROUP_AND_LIST,
    QUERY_ID_JOB_ALL,
    QUERY_ID_REFERENCE_BY_LIST,
    QUERY_ID_JOB_BY_JOBNAME,
    QUERY_ID_JOB_BY_DATASET_ID,
    QUERY_ID_DATASET_FOR_SAMPLES_BY_DATATYPE,
    QUERY_ID_DNASAMPLE_NAMES_BYLIST,
    QUERY_ID_DNASAMPLE_NAMES_ALL,
    QUERY_ID_MARKER_NAMES_BYLIST,
    QUERY_ID_PLATFORM_NAMES_BYLIST,
    QUERY_ID_LINKAGE_GROUP_NAMES_BYLIST,
    QUERY_ID_DNARUN_NAMES_BYLIST,
    QUERY_ID_GERMPLASM_BYLIST
}
