package org.gobiiproject.gobiimodel.types;

/**
 * Created by Phil on 6/15/2016.
 */
public enum GobiiFileProcessDir {
    RAW_USER_FILES,
    HDF5_FILES,
    LOADER_INSTRUCTIONS,
    LOADER_INTERMEDIATE_FILES,
    LOADER_INPROGRESS_FILES,
    EXTRACTOR_INSTRUCTIONS,
    EXTRACTOR_INPROGRESS,
    EXTRACTOR_DONE,
    EXTRACTOR_OUTPUT,
    EXTRACTOR_INPROGRESS,
    QC_NOTIFICATIONS
}
