== Overview

GOBii's internal documentation explains in detail how the web service infrastructure is architected. It is not necessary for a consumer of the GOBii web API to understand this in great detail. However, knowing a few things about it will make it easier to understand the web method documentation.  

=== Language and Framework
GOBii Web Services are implemented in Java with the Spring frameowrk. Virtually all calls conform to the same basic structure. For example, the /analyses POST method is as follows: 

[source,java]
----
    @RequestMapping(value = "/analyses", method = RequestMethod.POST)
    @ResponseBody
    public PayloadEnvelope<AnalysisDTO> createAnalysis(@ApiParam(required = true) @RequestBody PayloadEnvelope<AnalysisDTO> analysisPostEnvelope,
                                                       HttpServletRequest request,
                                                       HttpServletResponse response) {

        PayloadEnvelope<AnalysisDTO> returnVal = new PayloadEnvelope<>();
    
    	// populate returnVal . . . 

    	return returnVal; 
    }
----

Ther request and response are almost always wrapped in a type-parameterized PayloadEvenlope. In this case, the PayloadEnvelope is type-parameterized for the AnalysisDTO. Other methods are type parameterized according to the entity that they touch (e.g., the implementation of the /datasets POST method is type-parameterized for the DataSetDTO). 

=== The DTO Payload

The DTO objects are lightweight classes that contain simple data properties. They correspond roughly but not exactly to entities in the database (for example, in some cases a DTO defines a child collection of foreign-keyed entitites).

For a client of this application, however, the strongly-typed nature of the implementation is irrelvant: all request responses and bodies are conveyed in plain JSON, and it is the application's job to serialize and deserialize accordingly. What a client implementation must take into account, however, is the structure of the DTO that pertains to a specific all. From the reference section for each web method in this document, youcan navigate to the DTO definition. 


[[_requestresponsestructure]]
=== Request/Response Structure

The following illustrates the http body structure encompassed by the PayloadEnvelope. As mentioned above, it is the same for almost all responses as well as for the body of POST and PUT requests. 

[source,json]
----
	{
	   "payload":{
		  "linkCollection":{
			 "linksPerDataItem":[

			 ],
			 "exploreLinksPerDataItem":[

			 ]
		  },
		  "data":[

		  ]
	   },
	   "header":{
		  "gobiiProcessType":"",
		  "dtoHeaderAuth":{
			 "userName":null,
			 "password":null,
			 "token":"",
			 "gobiiCropType":""
		  },
		  "status":{
			 "succeeded":true,
			 "statusMessages":[

			 ],
			 "statusMessagesByCode":{

			 }
		  },
		  "pagination":null,
		  "gobiiVersion":"2.0_2018-07-31",
		  "cropType":""
	   }
	}
----

For requests, the following keys can be omitted:

* payload.linkCollection
* header

The content of the "data" array will vary depending on how the call is type-parameterized. For example, for a POST to the the /project resource, it will contain a project object, as defined by ProjectDTO.



=== Authentication

All calls except for /configsettings GET require a valid authentication token. The token can be acquired via a POST to the /auth resource with an empty body and the following request headers set:

* X-Username
* X-Password

The specified header values must, of course, be a valid GOBii username and password. Both values are expected to be unencrypted (https will provide encryption for the overall request stream). 

GOBii users must be defined in the system's LDAP and in the GOBii contact table. Accordingly, there can be two types of authentication failures:  

* 401 Unauthorized: the user does not authenticate to LDAP; 
* 403 Forbidden: the contact record does not exist. In this case, the error will indicate "Missing contact info for user <user-name> in crop database <crop-db>; a contact record must have username = <user-name>";  

When authentication succeeds, the response headers will contain an X-Auth-Token key whose value is a valid token. For subsequent requests, it is sufficient to supply X-Auth-Token in the request headers with the token that was received from the /auth POST. Some browsers prevent the client code from reading custom response headers. For such cases, the token value can also be retrieved from the "token" key in the "dtoHeaderAuth"  object. 


=== Error Handling

Errors internal to GOBii are reported in the "header" key accompanying the response. An example of how to retrieve error data is provided in the following code fragment.

[source,java]
----
if (!header.getStatus().isSucceeded() ||
        header
                .getStatus()
                .getStatusMessages()
                .stream()
                .filter(headerStatusMessage -> headerStatusMessage.getGobiiStatusLevel().equals(GobiiStatusLevel.VALIDATION))
                .count() > 0) {
    returnVal = true;
    System.out.println();
    System.out.println("*** Header errors: ");
    for (HeaderStatusMessage currentStatusMesage : header.getStatus().getStatusMessages()) {
        System.out.println(currentStatusMesage.getMessage());
    }
}
----


