export enum ExtractorItemType {
    UNKNOWN,
    ENTITY,
    MARKER_FILE,
    MARKER_LIST_ITEM,
    SAMPLE_LIST_ITEM,
    SAMPLE_FILE,
    EXPORT_FORMAT,
    CROP_TYPE,
    JOB_ID,
    SAMPLE_LIST_TYPE,
    LABEL,
    TREE_STRUCTURE}
