
export enum VertexNameType {

    VERTEX_TYPE_PROJECT,
    VERTEX_TYPE_SAMPLING_DATE,
    VERTEX_TYPE_GENOTYPING_PURPOSE,
    VERTEX_TYPE_DIVISION,
    VERTEX_TYPE_TRIAL_NAME,
    VERTEX_TYPE_EXPERIMENT,
    VERTEX_TYPE_DATASET,
    VERTEX_TYPE_DATASET_TYPE,
    VERTEX_TYPE_ANALYSIS,
    VERTEX_TYPE_ANALYSIS_TYPE,
    VERTEX_TYPE_REFERENCE_SAMPLE,
    VERTEX_TYPE_PLATFORM,
    VERTEX_TYPE_VENDOR,
    VERTEX_TYPE_PROTOCOL,
    VERTEX_TYPE_VENDOR_PROTOCOL,
    VERTEX_TYPE_MAPSET,
    VERTEX_TYPE_MAPSET_TYPE,
    VERTEX_TYPE_LINKAGE_GROUP,
    VERTEX_TYPE_GERMPLAM_SUBSPECIES,
    VERTEX_TYPE_GERMPLASM_SPECIES,
    VERTEX_TYPE_GERMPLASM_TYPE,
    VERTEX_TYPE_PRINCIPLE_INVESTIGATOR,
    MARKER,
    DNASAMPLE
}


